services:
  cvat_server:
    platform: linux/amd64
  cvat_ui:
    platform: linux/amd64
  cvat_worker_utils:
    platform: linux/amd64
  cvat_worker_import:
    platform: linux/amd64
  cvat_worker_export:
    platform: linux/amd64
  cvat_worker_annotation:
    platform: linux/amd64
  cvat_worker_webhooks:
    platform: linux/amd64
  cvat_worker_quality_reports:
    platform: linux/amd64
  cvat_worker_chunks:
    platform: linux/amd64
  cvat_worker_consensus:
    platform: linux/amd64
  cvat_transt_init:
    platform: linux/amd64
